"""Check asset links and required content."""
import httpx
from pathlib import Path
from app.checks.interface import CheckContext, CheckResult
from app.config import settings

AI_KEYWORDS = [
    "chatgpt",
    "copilot",
    "claude",
    "gemini",
    "openai",
    "anthropic",
    "ai-assisted",
    "ai generated",
    "generated by",
]


async def check_assets(context: CheckContext) -> CheckResult:
    """Check links, README, and AI disclosure."""
    score = 0
    details = {"broken_links": [], "missing_assets": [], "ai_disclosure": False}
    evidence = []

    # Check links
    async with httpx.AsyncClient(timeout=10) as client:
        links_to_check = []
        if context.scraped.github_url:
            links_to_check.append(("github", context.scraped.github_url))
        if context.scraped.video_url:
            links_to_check.append(("video", context.scraped.video_url))
        if context.scraped.slides_url:
            links_to_check.append(("slides", context.scraped.slides_url))

        for name, url in links_to_check:
            try:
                resp = await client.head(url, follow_redirects=True)
                if resp.status_code >= 400:
                    details["broken_links"].append(
                        {"name": name, "url": url, "status": resp.status_code}
                    )
                    score += 20
            except Exception:
                details["broken_links"].append(
                    {"name": name, "url": url, "status": "error"}
                )
                score += 20

    # Check README
    if context.repo_path:
        readmes = list(context.repo_path.glob("README*")) + list(
            context.repo_path.glob("readme*")
        )
        if not readmes:
            details["missing_assets"].append("README")
            score += 20

        # AI disclosure
        for rp in readmes:
            content = rp.read_text(errors="ignore").lower()
            if any(kw in content for kw in AI_KEYWORDS):
                details["ai_disclosure"] = True
                break

    # TODO: YouTube video timestamp verification
    # When HACKVERIFY_YOUTUBE_API_KEY is configured, check the demo video's
    # upload timestamp via YouTube Data API v3 against the hackathon date range.
    # If uploaded outside the hackathon window → score += 40, add to evidence.
    # Requires: google-api-python-client or direct REST call to:
    #   GET https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id}&key={api_key}
    # The video_id can be extracted from context.scraped.video_url.
    youtube_key = getattr(settings, "youtube_api_key", None)
    details["youtube_timestamp_check"] = "not implemented" if not youtube_key else "skipped"

    score = min(100, score)
    if score <= 30:
        status = "pass"
    elif score <= 60:
        status = "warn"
    else:
        status = "fail"

    return CheckResult(
        check_name="asset-integrity",
        check_category="asset_integrity",
        score=score,
        status=status,
        details=details,
        evidence=evidence,
    )
