"""Detect unmodified or minimally modified project templates."""

import re
from pathlib import Path

from app.checks.interface import CheckContext, CheckResult

# Template signatures - known fingerprints of common boilerplate
TEMPLATE_PATTERNS = {
    "create-react-app": {
        "files": ["src/App.js", "src/App.css", "src/index.js", "public/index.html"],
        "markers": [
            r"React\.js website",
            r"Edit.*src/App\.js.*save to reload",
            r"Learn React",
        ],
        "package_deps": ["react", "react-dom", "react-scripts"],
        "min_code_lines": 30,
    },
    "nextjs-init": {
        "files": ["app/page.tsx", "app/page.js", "app/layout.tsx", "app/layout.js", "pages/index.tsx"],
        "markers": [
            r"Get started by editing.*page",
            r"Next\.js",
            r"Deploy now",
        ],
        "package_deps": ["next"],
        "min_code_lines": 50,
    },
    "vue-cli": {
        "files": ["src/App.vue", "src/components/HelloWorld.vue"],
        "markers": [
            r"Welcome to Your Vue\.js App",
            r"vue-cli",
        ],
        "package_deps": ["vue"],
        "min_code_lines": 25,
    },
    "django-startproject": {
        "files": ["manage.py", "{project}/settings.py", "{project}/urls.py", "{project}/wsgi.py"],
        "markers": [
            r"Django settings",
            r"Generated by 'django-admin startproject'",
            r"INSTALLED_APPS.*django.contrib",
        ],
        "package_deps": ["django"],
        "min_code_lines": 100,
    },
    "flask-minimal": {
        "files": ["app.py", "main.py"],
        "markers": [
            r"__name__.*==.*__main__",
            r"app\.run.*debug=True",
        ],
        "package_deps": ["flask"],
        "min_code_lines": 10,
    },
    "express-generator": {
        "files": ["app.js", "routes/index.js", "routes/users.js", "views/index.jade"],
        "markers": [
            r"Express",
            r"app\.use\(.*logger",
        ],
        "package_deps": ["express"],
        "min_code_lines": 40,
    },
    "github-copilot-boilerplate": {
        "markers": [
            r"#.*TODO.*implement",
            r"#.*FIXME",
            r"pass.*#.*implement",
            r"return None.*#.*TODO",
        ],
        "is_boilerplate": True,
    },
}


def _detect_package_manager(repo: Path) -> str:
    """Detect which package manager files exist."""
    if (repo / "package.json").exists():
        return "npm"
    if (repo / "requirements.txt").exists():
        return "pip"
    if (repo / "Pipfile").exists():
        return "pipenv"
    if (repo / "Cargo.toml").exists():
        return "cargo"
    if (repo / "go.mod").exists():
        return "go"
    return "unknown"


def _count_meaningful_lines(repo: Path) -> tuple[int, int]:
    """Count total lines vs meaningful (non-comment, non-empty) lines."""
    total = 0
    meaningful = 0

    _SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "venv", "dist", "build"}
    _CODE_EXTS = {".py", ".js", ".ts", ".jsx", ".tsx", ".go", ".rs", ".java", ".c", ".cpp", ".rb", ".php"}

    for f in repo.rglob("*"):
        if not f.is_file():
            continue
        if any(p in _SKIP_DIRS for p in f.relative_to(repo).parts):
            continue
        if f.suffix not in _CODE_EXTS:
            continue

        try:
            content = f.read_text(errors="ignore")
            lines = content.split("\n")
            for line in lines:
                total += 1
                stripped = line.strip()
                # Skip empty lines and common comment patterns
                if stripped and not stripped.startswith(("#", "//", "/*", "*", "*/", "<!--")):
                    meaningful += 1
        except:
            pass

    return total, meaningful


def _check_template_markers(repo: Path) -> dict:
    """Check for template-specific markers."""
    results = {}

    for template_name, config in TEMPLATE_PATTERNS.items():
        matches = 0
        total_checks = 0

        # Check for marker strings in files
        markers = config.get("markers", [])
        for f in repo.rglob("*"):
            if not f.is_file():
                continue
            try:
                content = f.read_text(errors="ignore")
                for marker in markers:
                    if re.search(marker, content, re.IGNORECASE):
                        matches += 1
            except:
                pass

        total_checks += len(markers)

        # Check for expected files
        expected_files = config.get("files", [])
        files_found = 0
        for expected in expected_files:
            # Handle {project} wildcard
            if "{project}" in expected:
                # Look for any matching pattern
                pattern = expected.replace("{project}", "*")
                found = list(repo.glob(pattern))
                if found:
                    files_found += 1
            else:
                if (repo / expected).exists():
                    files_found += 1

        total_checks += len(expected_files)
        matches += files_found

        # Calculate confidence
        if total_checks > 0:
            confidence = matches / total_checks
        else:
            confidence = 0

        results[template_name] = {
            "confidence": confidence,
            "matches": matches,
            "total_checks": total_checks,
        }

    return results


def _check_boilerplate_ratio(repo: Path) -> float:
    """Calculate ratio of boilerplate to custom code."""
    total_lines = 0
    boilerplate_lines = 0

    _SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "venv", "dist", "build"}

    BOILERPLACE_PATTERNS = [
        r'^\s*import\s+React\s+from\s+[\'"]react[\'"]\s*$',
        r'^\s*import\s+\{\s*useState\s*,\s*useEffect\s*\}\s+from\s+[\'"]react[\'"]\s*$',
        r"^\s*def\s+main\(\):\s*pass\s*$",
        r'^\s*if\s+__name__\s*==\s*[\'"]__main__[\'"]:\s*pass\s*$',
        r"^\s*app\.listen\(.*PORT.*\)\s*$",
        r"^\s*export\s+default\s+function\s+\w+\(\)\s*\{\s*$",
    ]

    for f in repo.rglob("*"):
        if not f.is_file():
            continue
        if any(p in _SKIP_DIRS for p in f.relative_to(repo).parts):
            continue

        try:
            content = f.read_text(errors="ignore")
            lines = content.split("\n")
            for line in lines:
                total_lines += 1
                for pattern in BOILERPLACE_PATTERNS:
                    if re.match(pattern, line.strip()):
                        boilerplate_lines += 1
                        break
        except:
            pass

    if total_lines == 0:
        return 0

    return boilerplate_lines / total_lines


async def check_template(context: CheckContext) -> CheckResult:
    """Detect if the submission is an unmodified or minimally modified template."""
    if not context.repo_path:
        return CheckResult(
            check_name="template-detection",
            check_category="devpost_alignment",
            score=0,
            status="pass",
            details={"reason": "No repo available"},
        )

    # Count lines
    total_lines, meaningful_lines = _count_meaningful_lines(context.repo_path)

    if total_lines == 0:
        return CheckResult(
            check_name="template-detection",
            check_category="devpost_alignment",
            score=30,
            status="warn",
            details={"reason": "No code files found"},
        )

    # Check template signatures
    template_results = _check_template_markers(context.repo_path)

    # Find best matching template
    best_template = None
    best_confidence = 0
    for name, result in template_results.items():
        if result["confidence"] > best_confidence:
            best_confidence = result["confidence"]
            best_template = name

    # Check boilerplate ratio
    boilerplate_ratio = _check_boilerplate_ratio(context.repo_path)

    score = 0
    details = {
        "total_lines": total_lines,
        "meaningful_lines": meaningful_lines,
        "meaningful_ratio": meaningful_lines / total_lines if total_lines else 0,
        "best_template_match": best_template,
        "template_confidence": best_confidence,
        "boilerplate_ratio": boilerplate_ratio,
        "all_templates": template_results,
    }
    evidence = []

    # High template confidence = high score (suspicious)
    if best_confidence > 0.7:
        score += 50
        evidence.append(f"Strong match for '{best_template}' template ({best_confidence:.0%} confidence)")
    elif best_confidence > 0.5:
        score += 30
        evidence.append(f"Possible match for '{best_template}' template ({best_confidence:.0%} confidence)")

    # Very few meaningful lines
    if meaningful_lines < 50:
        score += 40
        evidence.append(f"Only {meaningful_lines} meaningful lines of code — likely unmodified template")
    elif meaningful_lines < 100:
        score += 20
        evidence.append(f"Only {meaningful_lines} meaningful lines — minimal customization")

    # Low meaningful ratio (lots of comments/empty lines = suspicious)
    meaningful_ratio = details["meaningful_ratio"]
    if meaningful_ratio < 0.5:
        score += 15
        evidence.append(f"Only {meaningful_ratio:.0%} of lines are actual code")

    # High boilerplate ratio
    if boilerplate_ratio > 0.3:
        score += 20
        evidence.append(f"High boilerplate ratio ({boilerplate_ratio:.0%}) — common import patterns")

    # Check for default README
    readme_paths = list(context.repo_path.glob("README*")) + list(context.repo_path.glob("readme*"))
    has_custom_readme = False
    for rp in readme_paths:
        content = rp.read_text(errors="ignore").lower()
        # If README mentions their project specifically, it's custom
        if context.scraped.title and context.scraped.title.lower() in content:
            has_custom_readme = True
            break
        # Check for template markers in README
        if any(marker in content for marker in ["getting started with create react app", "next.js project"]):
            score += 15
            evidence.append("README appears to be default template")

    score = min(100, score)
    status = "pass" if score <= 30 else "warn" if score <= 60 else "fail"

    return CheckResult(
        check_name="template-detection",
        check_category="devpost_alignment",
        score=score,
        status=status,
        details=details,
        evidence=evidence,
    )
