"""add self-hosted auth tables

Revision ID: 3e2ab12a7512
Revises: add_content_pages
Create Date: 2026-05-11 01:54:03.922614

"""

from typing import Sequence, Union

from alembic import op
import app.models  # noqa: F401
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "3e2ab12a7512"
down_revision: Union[str, Sequence[str], None] = "add_content_pages"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_providers",
        sa.Column("id", app.models.Guid(length=36), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_secret_encrypted", sa.Text(), nullable=False),
        sa.Column("authorize_url", sa.Text(), nullable=False),
        sa.Column("token_url", sa.Text(), nullable=False),
        sa.Column("userinfo_url", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", app.models.Guid(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False, unique=True, index=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hackathon_invites",
        sa.Column("id", app.models.Guid(length=36), nullable=False),
        sa.Column("hackathon_id", app.models.Guid(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("organizer", "participant", "judge", name="userrole", create_type=False),
            nullable=False,
        ),
        sa.Column("uses_remaining", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.add_column(
        "hackathons", sa.Column("registration_mode", sa.String(length=20), server_default="open", nullable=False)
    )
    op.add_column("oauth_accounts", sa.Column("access_token_encrypted", sa.Text(), nullable=True))
    op.add_column("oauth_accounts", sa.Column("refresh_token_encrypted", sa.Text(), nullable=True))
    op.add_column("oauth_accounts", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("users", sa.Column("password_reset_token_hash", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("password_reset_expires", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_expires")
    op.drop_column("users", "password_reset_token_hash")
    op.drop_column("users", "email_verified")
    op.drop_column("oauth_accounts", "expires_at")
    op.drop_column("oauth_accounts", "refresh_token_encrypted")
    op.drop_column("oauth_accounts", "access_token_encrypted")
    op.drop_column("hackathons", "registration_mode")
    op.drop_table("hackathon_invites")
    op.drop_table("refresh_tokens")
    op.drop_table("oauth_providers")
    # ### end Alembic commands ###
